import '../images/SVG/magnifying-glass.svg';
import '../images/SVG/heart.svg';
import '../images/SVG/twitter.svg';
import '../images/SVG/github.svg';
import '../images/SVG/linkedin.svg';
import '../images/SVG/chevron-down.svg';
import '../images/SVG/css32.svg';
import '../images/SVG/html5.svg';
import '../images/SVG/javascript.svg';
